//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_VOCATION { get; set; }
        public string CLIENT_CY { get; set; }
        public string CLIENT_ADDRESS { get; set; }
        public string CLIENT_BANK { get; set; }
        public string CLIENT_BANKNUM { get; set; }
        public int CLIENT_TYPE_ID { get; set; }
        public string CLIENT_USER { get; set; }
    }
}
