//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int ID { get; set; }
        public string LEAVE_NAME { get; set; }
        public int DEPART_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public int LEAVE_TYPE { get; set; }
        public string REASONS { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public int CHECK_FLAG { get; set; }
        public string CHECK_NAME { get; set; }
    }
}
