//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAWebEntities : DbContext
    {
        public OAWebEntities()
            : base("name=OAWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Type> C_Type { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Controller> Controllers { get; set; }
        public virtual DbSet<ControllerAction> ControllerActions { get; set; }
        public virtual DbSet<ControllRole> ControllRoles { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<OverTime> OverTimes { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<View_CRM> View_CRM { get; set; }
    }
}
