//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int ID { get; set; }
        public string PLANT_NAME { get; set; }
        public System.DateTime CREA_DATE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string CARRY_USER { get; set; }
        public string CREA_USER { get; set; }
        public string PLANT_INFO { get; set; }
        public int IN_FLAG { get; set; }
    }
}
